### ISSUE TITLE
PaN ontologies validation and sustainability

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#21]
_Origin: Review Report PMOC-857641-1-RP1_

__Recommendation 6 (Ontology Validation and Sustainability):__
In the second reporting period, the project must focus on validating the developed ontology. Likewise, the project should plan for the sustainability of the ontology targeting its proper documentation, standardization and update by the EOSC community.

**Comment by servansod** [comment]
PaNET ontology demonstration workshop - email from Carlo (04/02/2022):
> as part of the ontology implementation, we thought to extract the already existing SciCat implementation, and create a service covering the PaNET logic, data catalogue non-specific. You can find the details [here](https://github.com/ExPaNDS-eu/pan-ontologies-api) with some documentation, but please raise any possible issues, I will be happy to act accordingly. 
>
> For what concerns its adoption, we were thinking to organise a short workshop to go through it and explain how to use it.
>
> Please, if interested, fill in this [doodle](https://doodle.com/poll/pw2zmc3y3nusnpnh?utm_source=poll&utm_medium=link) for the date.

**Comment by minottic** [comment]
@servansod could you clarify a little what is expected here?

**Comment by servansod** [comment]
It's an issue to track what we do in response to our mid-term recommendation to better validate and sustain our PaNET ontology, so things related to:
- validation by the PaN community (workshops, presentations)
- plans for adoption by the PaN community e.g. in PaN-training, in the PaN-search API, in the PaN software catalogue
- improvements to the release management procedure: [see also dedicated issue there](https://github.com/ExPaNDS-eu/ExPaNDS-experimental-techniques-ontology/issues/46)
- ...

In terms of responsibilities, this falls between WP3 (Diamond) who is responsible for the ontology and WP1 (PSI) who is responsible for sustainability. I'd like to know who to assign this to.

**Comment by paulmillar** [comment]
One thing I've mentioned previously is that (in my opinion) sustainability will require a clear set of procedures for handling PaNET:
  * **On changes**: who reviews the proposed changes?  Who decides if new changes are accepted?  Who makes the changes in git?
  * **On releases**: what triggers a new release?  What is the release process?  Who has which roles during this process?
  * **On changing membership**: what happens if an RI wants to be more involved?  ... or wants to be less involved?
  * **On changing the rules**: how are these procedures updated?

IMHO, things like "validation" and "release process", although certainly important, are really just part of the bigger picture: part of the answer to these questions.

I fear that, without some clear procedures, PaNET will never be updated.  Over time, it will cease being useful, and will die.

I note that there is [a request for a new term](https://github.com/ExPaNDS-eu/ExPaNDS-experimental-techniques-ontology/issues/44) that has remained unresolved for _six months_!  This is while the ExPaNDS project is still running.

This means PaNET is already dying.

**Comment by spc93** [comment]
Hi Paul,

This are extremely important points. We plan to maintain a light-weight review and update process, but have struggled for resources in the last few months.

Regarding the new request, it was me who made the request, as a test, so it hasn’t really been sitting there for six months.

We certainly will need to develop a sustainable community approach to development.

Regards,
Steve

**Comment by paulmillar** [comment]
Hi Steve,

Thanks for clarifying the role of this issue.  Having a test issue to work with is certainly very helpful.

Do you have anything concrete (e.g., a document, meeting notes, etc) that describes the anticipated review and update process?

Cheers,
Paul.

**Comment by spc93** [comment]
Hi Paul,

Not in detail, no. It would be good to get a few people together to discuss how to do this, especially after ExPaNDS.

Cheers,
Steve

**Comment by paulmillar** [comment]
Indeed, that sounds like a good idea!

Perhaps we could put together a small team of people who would discuss these procedures, reach a consensus, and document them?

Would you be interested in kick-starting this process, Steve, perhaps with an initial meeting?

Cheers,
Paul.

**Comment by servansod** [comment]
PaNET group now monthly meeting and looking to carry on. Refer to overall sustainability issue #51.
