### ISSUE TITLE
unifying/improving spelling of names within the PaNET ontology

### ISSUE THREAD

**Issue by kara-mela** [ExPaNDS-eu/ExPaNDS#55]
I recognized that the terminology in PaNET is already widely unified, however I discovered some exceptions. It would be great if you could have a look at it:

1. ‘spin echo  scattering’ -> space
2. 'high resolution' is spelled without dash in almost all cases, except for 'high resolution neutron imaging'
3. some few names with abbreviations, please avoid
- EUV -> extreme ultra violet, UV -> ultra violet, VUV -> vacuum ultra violet
- 'IR photon probe' is the only case where IR is used instead of infrared
- 'time of flight' is the generally used spelling, exceptions are 'pulsed neutron TOF probe' and 'time-of-flight spectrometry'
- XMCD -> 'x-ray magnetic circular dichroism'

**Comment by kara-mela** [comment]
I just recognized, that my intention with point 1. is not visible: there is an additional space between 'echo' and 'scattering' that should be deleted.

**Comment by spc93** [comment]
Some comments:
- Names are copied from existing sources wherever possible.
- Adopted style is lower-case except for acronyms
- We assume the names are not case-sensitive in order to avoid a proliferation of terms using different case.
- We assume that there is no significant preference for label over alt-label, i.e. all labels have the same importance.
- Abbreviations and acronyms are treated as any other label/alt-label
- There are some mistakes!

**Comment by paulmillar** [comment]
We should probably capture this "style guide" in the PaNET SOP document --- I don't think it's there currently.

**Comment by paulmillar** [comment]
So, based on the above comments, should @kara-mela open a pull-request to resolve this issue?

**Comment by paulmillar** [comment]
> Some comments:

@spc93 Just to let you know, I've taken your comments and put them in the Standard Operating Procedure document as a starting point for a naming convention.
